package modelo;

public enum Distrito {
    VIANA_DO_CASTELO, BRAGANCA, VILA_REAL, BRAGA, PORTO, VISEU, GUARDA, AVEIRO, COIMBRA, CASTELO_BRANCO, LEIRIA, LISBOA, SANTAREM, SETUBAL, PORTALEGRE, BEJA, EVORA, FARO;
}
